export const GET_ALL_WORDS_SUCCESS = 'GET_ALL_WORDS_SUCCESS';
export const GET_ALL_WORDS_FAIL = 'GET_ALL_WORDS_FAIL';

export const GET_KNOWN_WORDS_SUCCESS = 'GET_KNOWN_WORDS_SUCCESS';
export const GET_KNOWN_WORDS_FAIL = 'GET_KNOWN_WORDS_FAIL';

export const GET_UNKNOWN_WORDS_SUCCESS = 'GET_UNKNOWN_WORDS_SUCCESS';
export const GET_UNKNOWN_WORDS_FAIL = 'GET_UNKNOWN_WORDS_FAIL';

export const GET_OWN_WORDS_SUCCESS = 'GET_OWN_WORDS_SUCCESS';
export const GET_OWN_WORDS_FAIL = 'GET_OWN_WORDS_FAIL';

// for future (when user will be can upload .json)
export const ADD_ALL_WORD_SUCCESS = 'ADD_ALL_WORD_SUCCESS';
export const ADD_ALL_WORD_FAIL = 'ADD_ALL_WORD_FAIL';

export const ADD_WORD_SUCCESS = 'ADD_ALL_WORD_SUCCESS';
export const ADD_WORD_FAIL = 'ADD_ALL_WORD_FAIL';

export const ADD_KNOWN_WORD_SUCCESS = 'ADD_KNOWN_WORD_SUCCESS';
export const ADD_KNOWN_WORD_FAIL = 'ADD_KNOWN_WORD_FAIL';

export const ADD_UNKNOWN_WORD_SUCCESS = 'ADD_UNKNOWN_WORD_SUCCESS';
export const ADD_UNKNOWN_WORD_FAIL = 'ADD_UNKNOWN_WORD_FAIL';

export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_FAIL = 'DELETE_WORD_FAIL';

export const CHANGE_WORD_SUCCESS = 'CHANGE_WORD_SUCCESS';
export const CHANGE_WORD_FAIL = 'CHANGE_WORD_FAIL';

